version: "3.8"
services:
  mysql:
    container_name: mysql-database
    image: "mysql:8.0"
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-secret}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-database}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-secret}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD:-no}"
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - mysql-net
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-database
    restart: unless-stopped
    networks:
      - mysql-net
    ports:
      - "${PHPMYADMIN_PORT:-8900}:80"
    environment:
      PMA_HOST: mysql
networks:
  mysql-net:
    driver: bridge
volumes:
  mysql-data:
    driver: local
